### ISSUE TITLE
Ball trajectory does not match ray pointing forward out of controller.

### ISSUE THREAD

**Issue by bryantvu** [bryantvu/Wonderland-Demo#4]
The balls shooting out of the controller do not match the direction of the ray that is pointing out from the front of the controller. Additionally, the 1st shot is always straight up.

https://user-images.githubusercontent.com/40374800/193368166-86aee4b4-f0e6-449d-ba04-da15c40b0cd5.mp4

**Comment by Squareys** [comment]
You need to use `inputType` "Ray(Left|Right)" instead of "Controller(Left|Right)". Check the CursorLeft/Right objects, they have it set up correctly. This will orient the attached-to object such that forward is the ray direction, not the orientation of the controller.

I assume you are using `getForward()` to retrieve the direction, then you may want to just move the component to the cursor object.

**Comment by bryantvu** [comment]
Okay, I changed the `inputType` for both controllers to Ray(Left|Right) and moved the ball-spawner component over to the cursor object. 

It's still having the same issue as before where the trajectory becomes more skewed as the controller is panned away from the cardinal axis (black).
![skew](https://user-images.githubusercontent.com/40374800/193708271-71c31d55-e67c-4b10-b69e-b31be2cba6ae.png)

https://user-images.githubusercontent.com/40374800/193708055-851d2f88-8f79-4334-86d2-8c27fb6215f8.mp4

I'm assuming that `this.object.getComponent('cursor').cursorRayObject.getForward(dir);` is not producing the same ray that I'm expecting (from the controller).

**Comment by bryantvu** [comment]
After confirming that `this.object.getComponent('cursor').cursorRayObject.getForward(dir);` does produce the expected vector, I realized that `ball-physics.js` was the issue. Currently creating a new linear physics component for the ball/bullet.
